### ISSUE TITLE
Add ability to bypass AA with HTTP header

### ISSUE THREAD

**Issue by dddpaul** [dddpaul/marathon-plugins-auth#27]
For example in config:

```
authentication:
  bypass_header: X-Marathon-Plugins-Auth-Disabled
```

**Comment by dddpaul** [comment]
For the sake of non-breaking changes -it may be more reasonable to enable AA only if special HTTP header is exists.

For example:

```
authentication:
  enabled

**Comment by dddpaul** [comment]
I think, this is the most flexible behaviour:

```yaml
authentication:
  enabled:
  configuration:
  	production_mode_enabled: true
  	trigger_header: X-Marathon-Plugin-Auth-Enabled
  	trigger_header_enabled: true
```

Parameters:

* `authentication.enabled` (optional): Disable or enable plugin. By default plugin is enabled.
* `authentication.configuration.production_mode_enabled` (optional): If `true`, then AA is enabled, but can be disabled by trigger header being set to `false`. If `false` then AA is disabled, but can be enabled by trigger header being set to `true`. By default is `true`.
* `authentication.configuration.trigger_header` (optional): HTTP header name for trigger on/off AA. By default is `null`, in this case triggering fuctionality is disabled.
* `authentication.configuration.trigger_header_enabled` (optional): Disable or enable triggering. By default is `false`, in this case triggering fuctionality is disabled.
